### ISSUE TITLE
Implement B-Tree

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#144]

**Comment by machendos** [comment]
https://github.com/metarhia/common/blob/b-tree/lib/b-tree.js
This is the basic implementation of B-Tree. Implemented methods: ``add, getEqual, getLess, getLarger, getBetween``. Method ``delete``  wasnt yet implemented , but this is a matter of time. When it becomes clear in what form data will come, it will be possible to implement the building of a tree on a data set. There are questions about opimization:
- 1) at the moment, the elements in the nodes are stored as an array. Perhaps  it would be better to remake this to a one-linked list? Since we never need a quick access to an item by index. And when you search for an element, you still look at the part of the array that precedes the desired one. However, adding elements to the middle will be faster and more enjoyable
- 2) For avoid mixins in the prototype of a tree, it is probably best to first assign all methods to some object, and then transfer them to the prototype by ``Obhect.assign()``?

**Comment by lundibundi** [comment]
@machendos open a PR in this repo please, we cannot properly review the code otherwise. (no place to comment on code, discuss etc)

**Comment by machendos** [comment]
@lundibundi https://github.com/metarhia/common/pull/159

**Comment by belochub** [comment]
Closed via https://github.com/metarhia/common/commit/1ac4d753b2ee189b4151bf738f51bb403a949ec4.
