### ISSUE TITLE
One set of tests

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#155]
We have `./test` (using `metatests`) and `./tests` (examples using `assert`)

**Comment by belochub** [comment]
The `./tests` directory was removed a long time ago in https://github.com/metarhia/common/commit/8a8b4472f34608044d0ac9edbb43507f795f2be3 long before this issue was opened.
This issue was probably supposed to be opened in the https://github.com/metarhia/metasync repo, but there is no need to transfer it now since it will duplicate https://github.com/metarhia/metasync/issues/378.
Thus, I think this issue can be closed.
