### ISSUE TITLE
Update to metatests 0.2.0

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#179]
Implementation @machendos
Review @lundibundi

**Comment by lundibundi** [comment]
Also, I'd stress that imo each test-file should be self contained and be able to run with just `node test-file.js` therefore it is important to remove all of the `global` usages. @tshemsedinov wdyt?
(before it was needed because the metatests worked that way, but now it should work with just `require` at the top of the test-file).

**Comment by tshemsedinov** [comment]
@lundibundi agree

**Comment by lundibundi** [comment]
@machendos please note that this comment https://github.com/metarhia/common/issues/179#issuecomment-417291536 applies to every refactoring you will make.
