### ISSUE TITLE
Comments to functional.js

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/common#66]
We need comments to generate docs
- [x] `replicate`
- [x] `maybe`
- [x] `curryTwice`
- [x] `applyArgs`

**Comment by belochub** [comment]
Closing this since all of the functions are now documented:

- [`replicate()`](https://github.com/metarhia/common#replicatecount-elem)
- [`maybe()`](https://github.com/metarhia/common#maybefn-defval-value)
- [`curryTwice()`](https://github.com/metarhia/common#currytwicefn)
- [`applyArgs()`](https://github.com/metarhia/common#applyargsargs)
